### ISSUE TITLE
header.php

### ISSUE THREAD

**Issue by byarranton** [BiancaShurey/JobApplication-Tracker#17]
The My Account dropdown in the nav bar requires the script imports shown below.

    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    <script src="js/bootstrap.min.js"></script>

**Comment by byarranton** [comment]
Clicking "sign out" in the My Account dropdown doesn't work (this was tested while in the Contacts page and resulted in "File not found")

**Comment by BiancaShurey** [comment]
FAQ page link doesn't work if logged in

**Comment by byarranton** [comment]
For the Calendar page, the script imports mentioned in the comment above cannot be used because they break the page. Bianca, can you come up with an alternative to get the navbar dropdown working on the Calendar page.
